/* File generated by the BNF Converter (bnfc 2.9.4). */

/*** Pretty Printer and Abstract Syntax Viewer ***/

#include <string>
#include "Printer.H"
#define INDENT_WIDTH 2


//You may wish to change render
void PrintAbsyn::render(Char c)
{
  if (c == '{')
  {
     onEmptyLine();
     bufAppend(c);
     _n_ = _n_ + INDENT_WIDTH;
     bufAppend('\n');
     indent();
  }
  else if (c == '(' || c == '[')
     bufAppend(c);
  else if (c == ')' || c == ']')
  {
     removeTrailingWhitespace();
     bufAppend(c);
     bufAppend(' ');
  }
  else if (c == '}')
  {
     _n_ = _n_ - INDENT_WIDTH;
     onEmptyLine();
     bufAppend(c);
     bufAppend('\n');
     indent();
  }
  else if (c == ',')
  {
     removeTrailingWhitespace();
     bufAppend(c);
     bufAppend(' ');
  }
  else if (c == ';')
  {
     removeTrailingWhitespace();
     bufAppend(c);
     bufAppend('\n');
     indent();
  }
  else if (c == ' ') bufAppend(c);
  else if (c == 0) return;
  else
  {
     bufAppend(c);
     bufAppend(' ');
  }
}

void PrintAbsyn::render(String s)
{
  render(s.c_str());
}

bool allIsSpace(const char *s)
{
  char c;
  while ((c = *s++))
    if (! isspace(c)) return false;
  return true;
}

void PrintAbsyn::render(const char *s)
{
  if (*s) /* C string not empty */
  {
    if (allIsSpace(s)) {
      backup();
      bufAppend(s);
    } else {
      bufAppend(s);
      bufAppend(' ');
    }
  }
}

void PrintAbsyn::indent()
{
  int n = _n_;
  while (--n >= 0)
    bufAppend(' ');
}

void PrintAbsyn::backup()
{
  if (cur_ && buf_[cur_ - 1] == ' ')
    buf_[--cur_] = 0;
}

void PrintAbsyn::removeTrailingSpaces()
{
  while (cur_ && buf_[cur_ - 1] == ' ') --cur_;
  buf_[cur_] = 0;
}

void PrintAbsyn::removeTrailingWhitespace()
{
  while (cur_ && (buf_[cur_ - 1] == ' ' || buf_[cur_ - 1] == '\n')) --cur_;
  buf_[cur_] = 0;
}

void PrintAbsyn::onEmptyLine()
{
  removeTrailingSpaces();
  if (cur_ && buf_[cur_ - 1 ] != '\n') bufAppend('\n');
  indent();
}

PrintAbsyn::PrintAbsyn(void)
{
  _i_ = 0; _n_ = 0;
  buf_ = 0;
  bufReset();
}

PrintAbsyn::~PrintAbsyn(void)
{
}

char *PrintAbsyn::print(Visitable *v)
{
  _i_ = 0; _n_ = 0;
  bufReset();
  v->accept(this);
  return buf_;
}

void PrintAbsyn::visitProgram(Program *p) {} //abstract class

void PrintAbsyn::visitProgramRoot(ProgramRoot *p)
{
  int oldi = _i_;
  if (oldi > 0) render(_L_PAREN);

  _i_ = 0; visitListStatement(p->liststatement_);

  if (oldi > 0) render(_R_PAREN);
  _i_ = oldi;
}

void PrintAbsyn::visitListExpr(ListExpr *listexpr)
{
  iterListExpr(listexpr->begin(), listexpr->end());
}

void PrintAbsyn::iterListExpr(ListExpr::const_iterator i, ListExpr::const_iterator j)
{
  if (i == j) return;
  if (i == j-1)
  { /* last */
    (*i)->accept(this);
  }
  else
  { /* cons */
    (*i)->accept(this); render(','); iterListExpr(i+1, j);
  }
}

void PrintAbsyn::visitExpr(Expr *p) {} //abstract class

void PrintAbsyn::visitWhere(Where *p)
{
  int oldi = _i_;
  if (oldi > 0) render(_L_PAREN);

  _i_ = 0; p->expr_1->accept(this);
  render("where");
  _i_ = 0; p->type_->accept(this);
  visitIdent(p->ident_);
  render('=');
  _i_ = 0; p->expr_2->accept(this);

  if (oldi > 0) render(_R_PAREN);
  _i_ = oldi;
}

void PrintAbsyn::visitMultiWhere(MultiWhere *p)
{
  int oldi = _i_;
  if (oldi > 0) render(_L_PAREN);

  _i_ = 0; p->expr_->accept(this);
  render("where");
  render('{');
  _i_ = 0; visitListWhereField_(p->listwherefield__);
  render('}');

  if (oldi > 0) render(_R_PAREN);
  _i_ = oldi;
}

void PrintAbsyn::visitAbstraction(Abstraction *p)
{
  int oldi = _i_;
  if (oldi > 0) render(_L_PAREN);

  render("fun");
  render('(');
  _i_ = 0; p->type_->accept(this);
  visitIdent(p->ident_);
  render(')');
  render('{');
  _i_ = 0; visitListStatement(p->liststatement_);
  render("ret");
  _i_ = 0; p->expr_->accept(this);
  render('}');

  if (oldi > 0) render(_R_PAREN);
  _i_ = oldi;
}

void PrintAbsyn::visitMultiAbstraction(MultiAbstraction *p)
{
  int oldi = _i_;
  if (oldi > 0) render(_L_PAREN);

  render("fun");
  render('(');
  _i_ = 0; visitListAbstractionField_(p->listabstractionfield__);
  render(')');
  render('{');
  _i_ = 0; visitListStatement(p->liststatement_);
  render("ret");
  _i_ = 0; p->expr_->accept(this);
  render('}');

  if (oldi > 0) render(_R_PAREN);
  _i_ = oldi;
}

void PrintAbsyn::visitApplication(Application *p)
{
  int oldi = _i_;
  if (oldi > 0) render(_L_PAREN);

  _i_ = 0; p->expr_1->accept(this);
  _i_ = 1; p->expr_2->accept(this);

  if (oldi > 0) render(_R_PAREN);
  _i_ = oldi;
}

void PrintAbsyn::visitTypeAbstraction(TypeAbstraction *p)
{
  int oldi = _i_;
  if (oldi > 0) render(_L_PAREN);

  render("uni");
  visitIdent(p->ident_);
  render("~>");
  _i_ = 0; p->expr_->accept(this);

  if (oldi > 0) render(_R_PAREN);
  _i_ = oldi;
}

void PrintAbsyn::visitTypeApplication(TypeApplication *p)
{
  int oldi = _i_;
  if (oldi > 0) render(_L_PAREN);

  _i_ = 0; p->expr_->accept(this);
  render('[');
  _i_ = 0; p->type_->accept(this);
  render(']');

  if (oldi > 0) render(_R_PAREN);
  _i_ = oldi;
}

void PrintAbsyn::visitConstTrue(ConstTrue *p)
{
  int oldi = _i_;
  if (oldi > 6) render(_L_PAREN);

  render("true");

  if (oldi > 6) render(_R_PAREN);
  _i_ = oldi;
}

void PrintAbsyn::visitConstFalse(ConstFalse *p)
{
  int oldi = _i_;
  if (oldi > 6) render(_L_PAREN);

  render("false");

  if (oldi > 6) render(_R_PAREN);
  _i_ = oldi;
}

void PrintAbsyn::visitConstZero(ConstZero *p)
{
  int oldi = _i_;
  if (oldi > 6) render(_L_PAREN);

  render("$0");

  if (oldi > 6) render(_R_PAREN);
  _i_ = oldi;
}

void PrintAbsyn::visitVar(Var *p)
{
  int oldi = _i_;
  if (oldi > 6) render(_L_PAREN);

  visitIdent(p->ident_);

  if (oldi > 6) render(_R_PAREN);
  _i_ = oldi;
}

void PrintAbsyn::visitConstInt(ConstInt *p)
{
  int oldi = _i_;
  if (oldi > 6) render(_L_PAREN);

  visitInteger(p->integer_);

  if (oldi > 6) render(_R_PAREN);
  _i_ = oldi;
}

void PrintAbsyn::visitConstReal(ConstReal *p)
{
  int oldi = _i_;
  if (oldi > 6) render(_L_PAREN);

  visitDouble(p->double_);

  if (oldi > 6) render(_R_PAREN);
  _i_ = oldi;
}

void PrintAbsyn::visitIf(If *p)
{
  int oldi = _i_;
  if (oldi > 1) render(_L_PAREN);

  render("if");
  _i_ = 1; p->expr_1->accept(this);
  render("then");
  _i_ = 1; p->expr_2->accept(this);
  render("else");
  _i_ = 1; p->expr_3->accept(this);

  if (oldi > 1) render(_R_PAREN);
  _i_ = oldi;
}

void PrintAbsyn::visitSucc(Succ *p)
{
  int oldi = _i_;
  if (oldi > 1) render(_L_PAREN);

  render("succ");
  _i_ = 1; p->expr_->accept(this);

  if (oldi > 1) render(_R_PAREN);
  _i_ = oldi;
}

void PrintAbsyn::visitPred(Pred *p)
{
  int oldi = _i_;
  if (oldi > 1) render(_L_PAREN);

  render("pred");
  _i_ = 1; p->expr_->accept(this);

  if (oldi > 1) render(_R_PAREN);
  _i_ = oldi;
}

void PrintAbsyn::visitIsZero(IsZero *p)
{
  int oldi = _i_;
  if (oldi > 1) render(_L_PAREN);

  render("iszero");
  _i_ = 1; p->expr_->accept(this);

  if (oldi > 1) render(_R_PAREN);
  _i_ = oldi;
}

void PrintAbsyn::visitFix(Fix *p)
{
  int oldi = _i_;
  if (oldi > 1) render(_L_PAREN);

  render("fix");
  _i_ = 1; p->expr_->accept(this);

  if (oldi > 1) render(_R_PAREN);
  _i_ = oldi;
}

void PrintAbsyn::visitTuple(Tuple *p)
{
  int oldi = _i_;
  if (oldi > 1) render(_L_PAREN);

  render('<');
  _i_ = 0; visitListExpr(p->listexpr_);
  render('>');

  if (oldi > 1) render(_R_PAREN);
  _i_ = oldi;
}

void PrintAbsyn::visitTupleGet(TupleGet *p)
{
  int oldi = _i_;
  if (oldi > 1) render(_L_PAREN);

  _i_ = 1; p->expr_->accept(this);
  render('.');
  visitInteger(p->integer_);

  if (oldi > 1) render(_R_PAREN);
  _i_ = oldi;
}

void PrintAbsyn::visitRecord(Record *p)
{
  int oldi = _i_;
  if (oldi > 1) render(_L_PAREN);

  render('{');
  _i_ = 0; visitListRecordField_(p->listrecordfield__);
  render('}');

  if (oldi > 1) render(_R_PAREN);
  _i_ = oldi;
}

void PrintAbsyn::visitRecordGet(RecordGet *p)
{
  int oldi = _i_;
  if (oldi > 1) render(_L_PAREN);

  _i_ = 1; p->expr_->accept(this);
  render('.');
  visitIdent(p->ident_);

  if (oldi > 1) render(_R_PAREN);
  _i_ = oldi;
}

void PrintAbsyn::visitVariant(Variant *p)
{
  int oldi = _i_;
  if (oldi > 1) render(_L_PAREN);

  render('<');
  visitIdent(p->ident_);
  render('=');
  _i_ = 0; p->expr_->accept(this);
  render('>');
  render("as");
  _i_ = 0; p->type_->accept(this);

  if (oldi > 1) render(_R_PAREN);
  _i_ = oldi;
}

void PrintAbsyn::visitVariantCase(VariantCase *p)
{
  int oldi = _i_;
  if (oldi > 1) render(_L_PAREN);

  render("case");
  _i_ = 0; p->expr_->accept(this);
  render("of");
  _i_ = 0; visitListVariantField_(p->listvariantfield__);

  if (oldi > 1) render(_R_PAREN);
  _i_ = oldi;
}

void PrintAbsyn::visitArray(Array *p)
{
  int oldi = _i_;
  if (oldi > 1) render(_L_PAREN);

  render('[');
  _i_ = 0; visitListExpr(p->listexpr_);
  render(']');

  if (oldi > 1) render(_R_PAREN);
  _i_ = oldi;
}

void PrintAbsyn::visitArrayGet(ArrayGet *p)
{
  int oldi = _i_;
  if (oldi > 1) render(_L_PAREN);

  render("get");
  render('(');
  _i_ = 0; p->expr_1->accept(this);
  _i_ = 0; p->expr_2->accept(this);
  render(')');

  if (oldi > 1) render(_R_PAREN);
  _i_ = oldi;
}

void PrintAbsyn::visitArrayPush(ArrayPush *p)
{
  int oldi = _i_;
  if (oldi > 1) render(_L_PAREN);

  render("push");
  render('(');
  _i_ = 0; p->expr_1->accept(this);
  _i_ = 0; p->expr_2->accept(this);
  render(')');

  if (oldi > 1) render(_R_PAREN);
  _i_ = oldi;
}

void PrintAbsyn::visitArrayPop(ArrayPop *p)
{
  int oldi = _i_;
  if (oldi > 1) render(_L_PAREN);

  render("pop");
  render('(');
  _i_ = 0; p->expr_->accept(this);
  render(')');

  if (oldi > 1) render(_R_PAREN);
  _i_ = oldi;
}

void PrintAbsyn::visitArrayLen(ArrayLen *p)
{
  int oldi = _i_;
  if (oldi > 1) render(_L_PAREN);

  render("len");
  render('(');
  _i_ = 0; p->expr_->accept(this);
  render(')');

  if (oldi > 1) render(_R_PAREN);
  _i_ = oldi;
}

void PrintAbsyn::visitToInt(ToInt *p)
{
  int oldi = _i_;
  if (oldi > 1) render(_L_PAREN);

  render("toInt");
  render('(');
  _i_ = 0; p->expr_->accept(this);
  render(')');

  if (oldi > 1) render(_R_PAREN);
  _i_ = oldi;
}

void PrintAbsyn::visitToReal(ToReal *p)
{
  int oldi = _i_;
  if (oldi > 1) render(_L_PAREN);

  render("toReal");
  render('(');
  _i_ = 0; p->expr_->accept(this);
  render(')');

  if (oldi > 1) render(_R_PAREN);
  _i_ = oldi;
}

void PrintAbsyn::visitReadInt(ReadInt *p)
{
  int oldi = _i_;
  if (oldi > 1) render(_L_PAREN);

  render("readInt");

  if (oldi > 1) render(_R_PAREN);
  _i_ = oldi;
}

void PrintAbsyn::visitReadReal(ReadReal *p)
{
  int oldi = _i_;
  if (oldi > 1) render(_L_PAREN);

  render("readReal");

  if (oldi > 1) render(_R_PAREN);
  _i_ = oldi;
}

void PrintAbsyn::visitWriteInt(WriteInt *p)
{
  int oldi = _i_;
  if (oldi > 1) render(_L_PAREN);

  render("writeInt");
  _i_ = 1; p->expr_->accept(this);

  if (oldi > 1) render(_R_PAREN);
  _i_ = oldi;
}

void PrintAbsyn::visitWriteReal(WriteReal *p)
{
  int oldi = _i_;
  if (oldi > 1) render(_L_PAREN);

  render("writeReal");
  _i_ = 1; p->expr_->accept(this);

  if (oldi > 1) render(_R_PAREN);
  _i_ = oldi;
}

void PrintAbsyn::visitReference(Reference *p)
{
  int oldi = _i_;
  if (oldi > 5) render(_L_PAREN);

  render("ref");
  _i_ = 5; p->expr_->accept(this);

  if (oldi > 5) render(_R_PAREN);
  _i_ = oldi;
}

void PrintAbsyn::visitDereference(Dereference *p)
{
  int oldi = _i_;
  if (oldi > 5) render(_L_PAREN);

  render('*');
  _i_ = 5; p->expr_->accept(this);

  if (oldi > 5) render(_R_PAREN);
  _i_ = oldi;
}

void PrintAbsyn::visitAddInt(AddInt *p)
{
  int oldi = _i_;
  if (oldi > 4) render(_L_PAREN);

  _i_ = 2; p->expr_1->accept(this);
  render("i+");
  _i_ = 2; p->expr_2->accept(this);

  if (oldi > 4) render(_R_PAREN);
  _i_ = oldi;
}

void PrintAbsyn::visitSubInt(SubInt *p)
{
  int oldi = _i_;
  if (oldi > 4) render(_L_PAREN);

  _i_ = 2; p->expr_1->accept(this);
  render("i-");
  _i_ = 2; p->expr_2->accept(this);

  if (oldi > 4) render(_R_PAREN);
  _i_ = oldi;
}

void PrintAbsyn::visitAddReal(AddReal *p)
{
  int oldi = _i_;
  if (oldi > 4) render(_L_PAREN);

  _i_ = 2; p->expr_1->accept(this);
  render("r+");
  _i_ = 2; p->expr_2->accept(this);

  if (oldi > 4) render(_R_PAREN);
  _i_ = oldi;
}

void PrintAbsyn::visitSubReal(SubReal *p)
{
  int oldi = _i_;
  if (oldi > 4) render(_L_PAREN);

  _i_ = 2; p->expr_1->accept(this);
  render("r-");
  _i_ = 2; p->expr_2->accept(this);

  if (oldi > 4) render(_R_PAREN);
  _i_ = oldi;
}

void PrintAbsyn::visitMulInt(MulInt *p)
{
  int oldi = _i_;
  if (oldi > 3) render(_L_PAREN);

  _i_ = 2; p->expr_1->accept(this);
  render("i*");
  _i_ = 2; p->expr_2->accept(this);

  if (oldi > 3) render(_R_PAREN);
  _i_ = oldi;
}

void PrintAbsyn::visitDivInt(DivInt *p)
{
  int oldi = _i_;
  if (oldi > 3) render(_L_PAREN);

  _i_ = 2; p->expr_1->accept(this);
  render("i/");
  _i_ = 2; p->expr_2->accept(this);

  if (oldi > 3) render(_R_PAREN);
  _i_ = oldi;
}

void PrintAbsyn::visitMulReal(MulReal *p)
{
  int oldi = _i_;
  if (oldi > 3) render(_L_PAREN);

  _i_ = 2; p->expr_1->accept(this);
  render("r*");
  _i_ = 2; p->expr_2->accept(this);

  if (oldi > 3) render(_R_PAREN);
  _i_ = oldi;
}

void PrintAbsyn::visitDivReal(DivReal *p)
{
  int oldi = _i_;
  if (oldi > 3) render(_L_PAREN);

  _i_ = 2; p->expr_1->accept(this);
  render("r/");
  _i_ = 2; p->expr_2->accept(this);

  if (oldi > 3) render(_R_PAREN);
  _i_ = oldi;
}

void PrintAbsyn::visitEquInt(EquInt *p)
{
  int oldi = _i_;
  if (oldi > 2) render(_L_PAREN);

  _i_ = 2; p->expr_1->accept(this);
  render("i=");
  _i_ = 2; p->expr_2->accept(this);

  if (oldi > 2) render(_R_PAREN);
  _i_ = oldi;
}

void PrintAbsyn::visitLesInt(LesInt *p)
{
  int oldi = _i_;
  if (oldi > 2) render(_L_PAREN);

  _i_ = 2; p->expr_1->accept(this);
  render("i<");
  _i_ = 2; p->expr_2->accept(this);

  if (oldi > 2) render(_R_PAREN);
  _i_ = oldi;
}

void PrintAbsyn::visitEquReal(EquReal *p)
{
  int oldi = _i_;
  if (oldi > 2) render(_L_PAREN);

  _i_ = 2; p->expr_1->accept(this);
  render("r=");
  _i_ = 2; p->expr_2->accept(this);

  if (oldi > 2) render(_R_PAREN);
  _i_ = oldi;
}

void PrintAbsyn::visitLesReal(LesReal *p)
{
  int oldi = _i_;
  if (oldi > 2) render(_L_PAREN);

  _i_ = 2; p->expr_1->accept(this);
  render("r<");
  _i_ = 2; p->expr_2->accept(this);

  if (oldi > 2) render(_R_PAREN);
  _i_ = oldi;
}

void PrintAbsyn::visitListAbstractionField_(ListAbstractionField_ *listabstractionfield_)
{
  iterListAbstractionField_(listabstractionfield_->begin(), listabstractionfield_->end());
}

void PrintAbsyn::iterListAbstractionField_(ListAbstractionField_::const_iterator i, ListAbstractionField_::const_iterator j)
{
  if (i == j) return;
  if (i == j-1)
  { /* last */
    (*i)->accept(this);
  }
  else
  { /* cons */
    (*i)->accept(this); render(','); iterListAbstractionField_(i+1, j);
  }
}

void PrintAbsyn::visitAbstractionField_(AbstractionField_ *p) {} //abstract class

void PrintAbsyn::visitAbstractionField(AbstractionField *p)
{
  int oldi = _i_;
  if (oldi > 0) render(_L_PAREN);

  _i_ = 0; p->type_->accept(this);
  visitIdent(p->ident_);

  if (oldi > 0) render(_R_PAREN);
  _i_ = oldi;
}

void PrintAbsyn::visitListWhereField_(ListWhereField_ *listwherefield_)
{
  iterListWhereField_(listwherefield_->begin(), listwherefield_->end());
}

void PrintAbsyn::iterListWhereField_(ListWhereField_::const_iterator i, ListWhereField_::const_iterator j)
{
  if (i == j) return;
  if (i == j-1)
  { /* last */
    (*i)->accept(this);
  }
  else
  { /* cons */
    (*i)->accept(this); render(','); iterListWhereField_(i+1, j);
  }
}

void PrintAbsyn::visitWhereField_(WhereField_ *p) {} //abstract class

void PrintAbsyn::visitWhereField(WhereField *p)
{
  int oldi = _i_;
  if (oldi > 0) render(_L_PAREN);

  visitIdent(p->ident_);
  render(':');
  _i_ = 0; p->type_->accept(this);
  render('=');
  _i_ = 1; p->expr_->accept(this);

  if (oldi > 0) render(_R_PAREN);
  _i_ = oldi;
}

void PrintAbsyn::visitListRecordField_(ListRecordField_ *listrecordfield_)
{
  iterListRecordField_(listrecordfield_->begin(), listrecordfield_->end());
}

void PrintAbsyn::iterListRecordField_(ListRecordField_::const_iterator i, ListRecordField_::const_iterator j)
{
  if (i == j) return;
  if (i == j-1)
  { /* last */
    (*i)->accept(this);
  }
  else
  { /* cons */
    (*i)->accept(this); render(','); iterListRecordField_(i+1, j);
  }
}

void PrintAbsyn::visitRecordField_(RecordField_ *p) {} //abstract class

void PrintAbsyn::visitRecordField(RecordField *p)
{
  int oldi = _i_;
  if (oldi > 0) render(_L_PAREN);

  visitIdent(p->ident_);
  render('=');
  _i_ = 0; p->expr_->accept(this);

  if (oldi > 0) render(_R_PAREN);
  _i_ = oldi;
}

void PrintAbsyn::visitListVariantField_(ListVariantField_ *listvariantfield_)
{
  iterListVariantField_(listvariantfield_->begin(), listvariantfield_->end());
}

void PrintAbsyn::iterListVariantField_(ListVariantField_::const_iterator i, ListVariantField_::const_iterator j)
{
  if (i == j) return;
  if (i == j-1)
  { /* last */
    (*i)->accept(this);
  }
  else
  { /* cons */
    (*i)->accept(this); render('|'); iterListVariantField_(i+1, j);
  }
}

void PrintAbsyn::visitVariantField_(VariantField_ *p) {} //abstract class

void PrintAbsyn::visitVariantField(VariantField *p)
{
  int oldi = _i_;
  if (oldi > 0) render(_L_PAREN);

  render('<');
  visitIdent(p->ident_1);
  render('=');
  visitIdent(p->ident_2);
  render('>');
  render("=>");
  _i_ = 0; p->expr_->accept(this);

  if (oldi > 0) render(_R_PAREN);
  _i_ = oldi;
}

void PrintAbsyn::visitStatement(Statement *p) {} //abstract class

void PrintAbsyn::visitImport(Import *p)
{
  int oldi = _i_;
  if (oldi > 0) render(_L_PAREN);

  render("import");
  render('<');
  visitIdent(p->ident_);
  render('>');

  if (oldi > 0) render(_R_PAREN);
  _i_ = oldi;
}

void PrintAbsyn::visitDefinition(Definition *p)
{
  int oldi = _i_;
  if (oldi > 0) render(_L_PAREN);

  render("def");
  _i_ = 0; p->type_->accept(this);
  visitIdent(p->ident_);
  render('=');
  _i_ = 0; p->expr_->accept(this);

  if (oldi > 0) render(_R_PAREN);
  _i_ = oldi;
}

void PrintAbsyn::visitMoveAssignment(MoveAssignment *p)
{
  int oldi = _i_;
  if (oldi > 0) render(_L_PAREN);

  _i_ = 0; p->expr_1->accept(this);
  render("<-");
  _i_ = 0; p->expr_2->accept(this);

  if (oldi > 0) render(_R_PAREN);
  _i_ = oldi;
}

void PrintAbsyn::visitCopyAssignment(CopyAssignment *p)
{
  int oldi = _i_;
  if (oldi > 0) render(_L_PAREN);

  _i_ = 0; p->expr_1->accept(this);
  render(":=");
  _i_ = 0; p->expr_2->accept(this);

  if (oldi > 0) render(_R_PAREN);
  _i_ = oldi;
}

void PrintAbsyn::visitIfStatement(IfStatement *p)
{
  int oldi = _i_;
  if (oldi > 0) render(_L_PAREN);

  render("if");
  _i_ = 0; p->expr_->accept(this);
  render('{');
  _i_ = 0; visitListStatement(p->liststatement_);
  render('}');

  if (oldi > 0) render(_R_PAREN);
  _i_ = oldi;
}

void PrintAbsyn::visitIfElseStatement(IfElseStatement *p)
{
  int oldi = _i_;
  if (oldi > 0) render(_L_PAREN);

  render("if");
  _i_ = 0; p->expr_->accept(this);
  render('{');
  _i_ = 0; visitListStatement(p->liststatement_1);
  render('}');
  render("else");
  render('{');
  _i_ = 0; visitListStatement(p->liststatement_2);
  render('}');

  if (oldi > 0) render(_R_PAREN);
  _i_ = oldi;
}

void PrintAbsyn::visitLoop(Loop *p)
{
  int oldi = _i_;
  if (oldi > 0) render(_L_PAREN);

  render("loop");
  render('{');
  _i_ = 0; visitListStatement(p->liststatement_);
  render('}');

  if (oldi > 0) render(_R_PAREN);
  _i_ = oldi;
}

void PrintAbsyn::visitBreak(Break *p)
{
  int oldi = _i_;
  if (oldi > 0) render(_L_PAREN);

  render("break");

  if (oldi > 0) render(_R_PAREN);
  _i_ = oldi;
}

void PrintAbsyn::visitContinue(Continue *p)
{
  int oldi = _i_;
  if (oldi > 0) render(_L_PAREN);

  render("continue");

  if (oldi > 0) render(_R_PAREN);
  _i_ = oldi;
}

void PrintAbsyn::visitReturn(Return *p)
{
  int oldi = _i_;
  if (oldi > 0) render(_L_PAREN);

  render("return");

  if (oldi > 0) render(_R_PAREN);
  _i_ = oldi;
}

void PrintAbsyn::visitEval(Eval *p)
{
  int oldi = _i_;
  if (oldi > 0) render(_L_PAREN);

  render("eval");
  _i_ = 0; p->expr_->accept(this);

  if (oldi > 0) render(_R_PAREN);
  _i_ = oldi;
}

void PrintAbsyn::visitListStatement(ListStatement *liststatement)
{
  iterListStatement(liststatement->begin(), liststatement->end());
}

void PrintAbsyn::iterListStatement(ListStatement::const_iterator i, ListStatement::const_iterator j)
{
  if (i == j) return;
  if (i == j-1)
  { /* last */
    (*i)->accept(this);
  }
  else
  { /* cons */
    (*i)->accept(this); render(';'); iterListStatement(i+1, j);
  }
}

void PrintAbsyn::visitListType(ListType *listtype)
{
  iterListType(listtype->begin(), listtype->end());
}

void PrintAbsyn::iterListType(ListType::const_iterator i, ListType::const_iterator j)
{
  if (i == j) return;
  if (i == j-1)
  { /* last */
    (*i)->accept(this);
  }
  else
  { /* cons */
    (*i)->accept(this); render(','); iterListType(i+1, j);
  }
}

void PrintAbsyn::visitType(Type *p) {} //abstract class

void PrintAbsyn::visitAutoType(AutoType *p)
{
  int oldi = _i_;
  if (oldi > 0) render(_L_PAREN);

  render('_');

  if (oldi > 0) render(_R_PAREN);
  _i_ = oldi;
}

void PrintAbsyn::visitBoolType(BoolType *p)
{
  int oldi = _i_;
  if (oldi > 0) render(_L_PAREN);

  render("Bool");

  if (oldi > 0) render(_R_PAREN);
  _i_ = oldi;
}

void PrintAbsyn::visitNatType(NatType *p)
{
  int oldi = _i_;
  if (oldi > 0) render(_L_PAREN);

  render("Nat");

  if (oldi > 0) render(_R_PAREN);
  _i_ = oldi;
}

void PrintAbsyn::visitRefType(RefType *p)
{
  int oldi = _i_;
  if (oldi > 0) render(_L_PAREN);

  render("Ref");
  _i_ = 0; p->type_->accept(this);

  if (oldi > 0) render(_R_PAREN);
  _i_ = oldi;
}

void PrintAbsyn::visitVarType(VarType *p)
{
  int oldi = _i_;
  if (oldi > 0) render(_L_PAREN);

  visitIdent(p->ident_);

  if (oldi > 0) render(_R_PAREN);
  _i_ = oldi;
}

void PrintAbsyn::visitUniType(UniType *p)
{
  int oldi = _i_;
  if (oldi > 0) render(_L_PAREN);

  render('%');
  visitIdent(p->ident_);
  render('.');
  _i_ = 0; p->type_->accept(this);

  if (oldi > 0) render(_R_PAREN);
  _i_ = oldi;
}

void PrintAbsyn::visitFunType(FunType *p)
{
  int oldi = _i_;
  if (oldi > 0) render(_L_PAREN);

  _i_ = 0; p->type_1->accept(this);
  render("->");
  _i_ = 0; p->type_2->accept(this);

  if (oldi > 0) render(_R_PAREN);
  _i_ = oldi;
}

void PrintAbsyn::visitTupleType(TupleType *p)
{
  int oldi = _i_;
  if (oldi > 0) render(_L_PAREN);

  render('<');
  _i_ = 0; visitListType(p->listtype_);
  render('>');

  if (oldi > 0) render(_R_PAREN);
  _i_ = oldi;
}

void PrintAbsyn::visitRecordType(RecordType *p)
{
  int oldi = _i_;
  if (oldi > 0) render(_L_PAREN);

  render('{');
  _i_ = 0; visitListRecordTypeField_(p->listrecordtypefield__);
  render('}');

  if (oldi > 0) render(_R_PAREN);
  _i_ = oldi;
}

void PrintAbsyn::visitVariantType(VariantType *p)
{
  int oldi = _i_;
  if (oldi > 0) render(_L_PAREN);

  render('<');
  _i_ = 0; visitListVariantTypeField_(p->listvarianttypefield__);
  render('>');

  if (oldi > 0) render(_R_PAREN);
  _i_ = oldi;
}

void PrintAbsyn::visitArrayType(ArrayType *p)
{
  int oldi = _i_;
  if (oldi > 0) render(_L_PAREN);

  render('[');
  _i_ = 0; p->type_->accept(this);
  render(']');

  if (oldi > 0) render(_R_PAREN);
  _i_ = oldi;
}

void PrintAbsyn::visitIntType(IntType *p)
{
  int oldi = _i_;
  if (oldi > 0) render(_L_PAREN);

  render("Int");

  if (oldi > 0) render(_R_PAREN);
  _i_ = oldi;
}

void PrintAbsyn::visitRealType(RealType *p)
{
  int oldi = _i_;
  if (oldi > 0) render(_L_PAREN);

  render("Real");

  if (oldi > 0) render(_R_PAREN);
  _i_ = oldi;
}

void PrintAbsyn::visitListRecordTypeField_(ListRecordTypeField_ *listrecordtypefield_)
{
  iterListRecordTypeField_(listrecordtypefield_->begin(), listrecordtypefield_->end());
}

void PrintAbsyn::iterListRecordTypeField_(ListRecordTypeField_::const_iterator i, ListRecordTypeField_::const_iterator j)
{
  if (i == j) return;
  if (i == j-1)
  { /* last */
    (*i)->accept(this);
  }
  else
  { /* cons */
    (*i)->accept(this); render(','); iterListRecordTypeField_(i+1, j);
  }
}

void PrintAbsyn::visitRecordTypeField_(RecordTypeField_ *p) {} //abstract class

void PrintAbsyn::visitRecordTypeField(RecordTypeField *p)
{
  int oldi = _i_;
  if (oldi > 0) render(_L_PAREN);

  visitIdent(p->ident_);
  render(':');
  _i_ = 0; p->type_->accept(this);

  if (oldi > 0) render(_R_PAREN);
  _i_ = oldi;
}

void PrintAbsyn::visitListVariantTypeField_(ListVariantTypeField_ *listvarianttypefield_)
{
  iterListVariantTypeField_(listvarianttypefield_->begin(), listvarianttypefield_->end());
}

void PrintAbsyn::iterListVariantTypeField_(ListVariantTypeField_::const_iterator i, ListVariantTypeField_::const_iterator j)
{
  if (i == j) return;
  if (i == j-1)
  { /* last */
    (*i)->accept(this);
  }
  else
  { /* cons */
    (*i)->accept(this); render(','); iterListVariantTypeField_(i+1, j);
  }
}

void PrintAbsyn::visitVariantTypeField_(VariantTypeField_ *p) {} //abstract class

void PrintAbsyn::visitVariantTypeField(VariantTypeField *p)
{
  int oldi = _i_;
  if (oldi > 0) render(_L_PAREN);

  visitIdent(p->ident_);
  render(':');
  _i_ = 0; p->type_->accept(this);

  if (oldi > 0) render(_R_PAREN);
  _i_ = oldi;
}

void PrintAbsyn::visitInteger(Integer i)
{
  char tmp[20];
  sprintf(tmp, "%d", i);
  render(tmp);
}

void PrintAbsyn::visitDouble(Double d)
{
  char tmp[24];
  sprintf(tmp, "%.15g", d);
  render(tmp);
}

void PrintAbsyn::visitChar(Char c)
{
  char tmp[4];
  sprintf(tmp, "'%c'", c);
  render(tmp);
}

void PrintAbsyn::visitString(String s)
{
  bufAppend('\"');
  bufAppend(s);
  bufAppend('\"');
  bufAppend(' ');
}

void PrintAbsyn::visitIdent(String s)
{
  render(s);
}

ShowAbsyn::ShowAbsyn(void)
{
  buf_ = 0;
  bufReset();
}

ShowAbsyn::~ShowAbsyn(void)
{
}

char *ShowAbsyn::show(Visitable *v)
{
  bufReset();
  v->accept(this);
  return buf_;
}

void ShowAbsyn::visitProgram(Program *p) {} //abstract class

void ShowAbsyn::visitProgramRoot(ProgramRoot *p)
{
  bufAppend('(');
  bufAppend("ProgramRoot");
  bufAppend(' ');
  bufAppend('[');
  if (p->liststatement_)  p->liststatement_->accept(this);
  bufAppend(']');
  bufAppend(')');
}
void ShowAbsyn::visitListExpr(ListExpr *listexpr)
{
  for (ListExpr::const_iterator i = listexpr->begin() ; i != listexpr->end() ; ++i)
  {
    (*i)->accept(this);
    if (i != listexpr->end() - 1) bufAppend(", ");
  }
}

void ShowAbsyn::visitExpr(Expr *p) {} //abstract class

void ShowAbsyn::visitWhere(Where *p)
{
  bufAppend('(');
  bufAppend("Where");
  bufAppend(' ');
  p->expr_1->accept(this);
  bufAppend(' ');
  bufAppend('[');
  if (p->type_)  p->type_->accept(this);
  bufAppend(']');
  bufAppend(' ');
  visitIdent(p->ident_);
  bufAppend(' ');
  p->expr_2->accept(this);
  bufAppend(')');
}
void ShowAbsyn::visitMultiWhere(MultiWhere *p)
{
  bufAppend('(');
  bufAppend("MultiWhere");
  bufAppend(' ');
  bufAppend('[');
  if (p->expr_)  p->expr_->accept(this);
  bufAppend(']');
  bufAppend(' ');
  bufAppend('[');
  if (p->listwherefield__)  p->listwherefield__->accept(this);
  bufAppend(']');
  bufAppend(' ');
  bufAppend(')');
}
void ShowAbsyn::visitAbstraction(Abstraction *p)
{
  bufAppend('(');
  bufAppend("Abstraction");
  bufAppend(' ');
  bufAppend('[');
  if (p->type_)  p->type_->accept(this);
  bufAppend(']');
  bufAppend(' ');
  visitIdent(p->ident_);
  bufAppend(' ');
  bufAppend('[');
  if (p->liststatement_)  p->liststatement_->accept(this);
  bufAppend(']');
  bufAppend(' ');
  bufAppend('[');
  if (p->expr_)  p->expr_->accept(this);
  bufAppend(']');
  bufAppend(' ');
  bufAppend(')');
}
void ShowAbsyn::visitMultiAbstraction(MultiAbstraction *p)
{
  bufAppend('(');
  bufAppend("MultiAbstraction");
  bufAppend(' ');
  bufAppend('[');
  if (p->listabstractionfield__)  p->listabstractionfield__->accept(this);
  bufAppend(']');
  bufAppend(' ');
  bufAppend('[');
  if (p->liststatement_)  p->liststatement_->accept(this);
  bufAppend(']');
  bufAppend(' ');
  bufAppend('[');
  if (p->expr_)  p->expr_->accept(this);
  bufAppend(']');
  bufAppend(' ');
  bufAppend(')');
}
void ShowAbsyn::visitApplication(Application *p)
{
  bufAppend('(');
  bufAppend("Application");
  bufAppend(' ');
  p->expr_1->accept(this);
  bufAppend(' ');
  p->expr_2->accept(this);
  bufAppend(')');
}
void ShowAbsyn::visitTypeAbstraction(TypeAbstraction *p)
{
  bufAppend('(');
  bufAppend("TypeAbstraction");
  bufAppend(' ');
  visitIdent(p->ident_);
  bufAppend(' ');
  bufAppend('[');
  if (p->expr_)  p->expr_->accept(this);
  bufAppend(']');
  bufAppend(')');
}
void ShowAbsyn::visitTypeApplication(TypeApplication *p)
{
  bufAppend('(');
  bufAppend("TypeApplication");
  bufAppend(' ');
  bufAppend('[');
  if (p->expr_)  p->expr_->accept(this);
  bufAppend(']');
  bufAppend(' ');
  bufAppend('[');
  if (p->type_)  p->type_->accept(this);
  bufAppend(']');
  bufAppend(' ');
  bufAppend(')');
}
void ShowAbsyn::visitConstTrue(ConstTrue *p)
{
  bufAppend("ConstTrue");
}
void ShowAbsyn::visitConstFalse(ConstFalse *p)
{
  bufAppend("ConstFalse");
}
void ShowAbsyn::visitConstZero(ConstZero *p)
{
  bufAppend("ConstZero");
}
void ShowAbsyn::visitVar(Var *p)
{
  bufAppend('(');
  bufAppend("Var");
  bufAppend(' ');
  visitIdent(p->ident_);
  bufAppend(')');
}
void ShowAbsyn::visitConstInt(ConstInt *p)
{
  bufAppend('(');
  bufAppend("ConstInt");
  bufAppend(' ');
  visitInteger(p->integer_);
  bufAppend(')');
}
void ShowAbsyn::visitConstReal(ConstReal *p)
{
  bufAppend('(');
  bufAppend("ConstReal");
  bufAppend(' ');
  visitDouble(p->double_);
  bufAppend(')');
}
void ShowAbsyn::visitIf(If *p)
{
  bufAppend('(');
  bufAppend("If");
  bufAppend(' ');
  p->expr_1->accept(this);
  bufAppend(' ');
  p->expr_2->accept(this);
  bufAppend(' ');
  p->expr_3->accept(this);
  bufAppend(')');
}
void ShowAbsyn::visitSucc(Succ *p)
{
  bufAppend('(');
  bufAppend("Succ");
  bufAppend(' ');
  bufAppend('[');
  if (p->expr_)  p->expr_->accept(this);
  bufAppend(']');
  bufAppend(')');
}
void ShowAbsyn::visitPred(Pred *p)
{
  bufAppend('(');
  bufAppend("Pred");
  bufAppend(' ');
  bufAppend('[');
  if (p->expr_)  p->expr_->accept(this);
  bufAppend(']');
  bufAppend(')');
}
void ShowAbsyn::visitIsZero(IsZero *p)
{
  bufAppend('(');
  bufAppend("IsZero");
  bufAppend(' ');
  bufAppend('[');
  if (p->expr_)  p->expr_->accept(this);
  bufAppend(']');
  bufAppend(')');
}
void ShowAbsyn::visitFix(Fix *p)
{
  bufAppend('(');
  bufAppend("Fix");
  bufAppend(' ');
  bufAppend('[');
  if (p->expr_)  p->expr_->accept(this);
  bufAppend(']');
  bufAppend(')');
}
void ShowAbsyn::visitTuple(Tuple *p)
{
  bufAppend('(');
  bufAppend("Tuple");
  bufAppend(' ');
  bufAppend('[');
  if (p->listexpr_)  p->listexpr_->accept(this);
  bufAppend(']');
  bufAppend(' ');
  bufAppend(')');
}
void ShowAbsyn::visitTupleGet(TupleGet *p)
{
  bufAppend('(');
  bufAppend("TupleGet");
  bufAppend(' ');
  bufAppend('[');
  if (p->expr_)  p->expr_->accept(this);
  bufAppend(']');
  bufAppend(' ');
  visitInteger(p->integer_);
  bufAppend(')');
}
void ShowAbsyn::visitRecord(Record *p)
{
  bufAppend('(');
  bufAppend("Record");
  bufAppend(' ');
  bufAppend('[');
  if (p->listrecordfield__)  p->listrecordfield__->accept(this);
  bufAppend(']');
  bufAppend(' ');
  bufAppend(')');
}
void ShowAbsyn::visitRecordGet(RecordGet *p)
{
  bufAppend('(');
  bufAppend("RecordGet");
  bufAppend(' ');
  bufAppend('[');
  if (p->expr_)  p->expr_->accept(this);
  bufAppend(']');
  bufAppend(' ');
  visitIdent(p->ident_);
  bufAppend(')');
}
void ShowAbsyn::visitVariant(Variant *p)
{
  bufAppend('(');
  bufAppend("Variant");
  bufAppend(' ');
  visitIdent(p->ident_);
  bufAppend(' ');
  bufAppend('[');
  if (p->expr_)  p->expr_->accept(this);
  bufAppend(']');
  bufAppend(' ');
  bufAppend('[');
  if (p->type_)  p->type_->accept(this);
  bufAppend(']');
  bufAppend(')');
}
void ShowAbsyn::visitVariantCase(VariantCase *p)
{
  bufAppend('(');
  bufAppend("VariantCase");
  bufAppend(' ');
  bufAppend('[');
  if (p->expr_)  p->expr_->accept(this);
  bufAppend(']');
  bufAppend(' ');
  bufAppend('[');
  if (p->listvariantfield__)  p->listvariantfield__->accept(this);
  bufAppend(']');
  bufAppend(')');
}
void ShowAbsyn::visitArray(Array *p)
{
  bufAppend('(');
  bufAppend("Array");
  bufAppend(' ');
  bufAppend('[');
  if (p->listexpr_)  p->listexpr_->accept(this);
  bufAppend(']');
  bufAppend(' ');
  bufAppend(')');
}
void ShowAbsyn::visitArrayGet(ArrayGet *p)
{
  bufAppend('(');
  bufAppend("ArrayGet");
  bufAppend(' ');
  p->expr_1->accept(this);
  bufAppend(' ');
  p->expr_2->accept(this);
  bufAppend(' ');
  bufAppend(')');
}
void ShowAbsyn::visitArrayPush(ArrayPush *p)
{
  bufAppend('(');
  bufAppend("ArrayPush");
  bufAppend(' ');
  p->expr_1->accept(this);
  bufAppend(' ');
  p->expr_2->accept(this);
  bufAppend(' ');
  bufAppend(')');
}
void ShowAbsyn::visitArrayPop(ArrayPop *p)
{
  bufAppend('(');
  bufAppend("ArrayPop");
  bufAppend(' ');
  bufAppend('[');
  if (p->expr_)  p->expr_->accept(this);
  bufAppend(']');
  bufAppend(' ');
  bufAppend(')');
}
void ShowAbsyn::visitArrayLen(ArrayLen *p)
{
  bufAppend('(');
  bufAppend("ArrayLen");
  bufAppend(' ');
  bufAppend('[');
  if (p->expr_)  p->expr_->accept(this);
  bufAppend(']');
  bufAppend(' ');
  bufAppend(')');
}
void ShowAbsyn::visitToInt(ToInt *p)
{
  bufAppend('(');
  bufAppend("ToInt");
  bufAppend(' ');
  bufAppend('[');
  if (p->expr_)  p->expr_->accept(this);
  bufAppend(']');
  bufAppend(' ');
  bufAppend(')');
}
void ShowAbsyn::visitToReal(ToReal *p)
{
  bufAppend('(');
  bufAppend("ToReal");
  bufAppend(' ');
  bufAppend('[');
  if (p->expr_)  p->expr_->accept(this);
  bufAppend(']');
  bufAppend(' ');
  bufAppend(')');
}
void ShowAbsyn::visitReadInt(ReadInt *p)
{
  bufAppend("ReadInt");
}
void ShowAbsyn::visitReadReal(ReadReal *p)
{
  bufAppend("ReadReal");
}
void ShowAbsyn::visitWriteInt(WriteInt *p)
{
  bufAppend('(');
  bufAppend("WriteInt");
  bufAppend(' ');
  bufAppend('[');
  if (p->expr_)  p->expr_->accept(this);
  bufAppend(']');
  bufAppend(')');
}
void ShowAbsyn::visitWriteReal(WriteReal *p)
{
  bufAppend('(');
  bufAppend("WriteReal");
  bufAppend(' ');
  bufAppend('[');
  if (p->expr_)  p->expr_->accept(this);
  bufAppend(']');
  bufAppend(')');
}
void ShowAbsyn::visitReference(Reference *p)
{
  bufAppend('(');
  bufAppend("Reference");
  bufAppend(' ');
  bufAppend('[');
  if (p->expr_)  p->expr_->accept(this);
  bufAppend(']');
  bufAppend(')');
}
void ShowAbsyn::visitDereference(Dereference *p)
{
  bufAppend('(');
  bufAppend("Dereference");
  bufAppend(' ');
  bufAppend('[');
  if (p->expr_)  p->expr_->accept(this);
  bufAppend(']');
  bufAppend(')');
}
void ShowAbsyn::visitAddInt(AddInt *p)
{
  bufAppend('(');
  bufAppend("AddInt");
  bufAppend(' ');
  p->expr_1->accept(this);
  bufAppend(' ');
  p->expr_2->accept(this);
  bufAppend(')');
}
void ShowAbsyn::visitSubInt(SubInt *p)
{
  bufAppend('(');
  bufAppend("SubInt");
  bufAppend(' ');
  p->expr_1->accept(this);
  bufAppend(' ');
  p->expr_2->accept(this);
  bufAppend(')');
}
void ShowAbsyn::visitAddReal(AddReal *p)
{
  bufAppend('(');
  bufAppend("AddReal");
  bufAppend(' ');
  p->expr_1->accept(this);
  bufAppend(' ');
  p->expr_2->accept(this);
  bufAppend(')');
}
void ShowAbsyn::visitSubReal(SubReal *p)
{
  bufAppend('(');
  bufAppend("SubReal");
  bufAppend(' ');
  p->expr_1->accept(this);
  bufAppend(' ');
  p->expr_2->accept(this);
  bufAppend(')');
}
void ShowAbsyn::visitMulInt(MulInt *p)
{
  bufAppend('(');
  bufAppend("MulInt");
  bufAppend(' ');
  p->expr_1->accept(this);
  bufAppend(' ');
  p->expr_2->accept(this);
  bufAppend(')');
}
void ShowAbsyn::visitDivInt(DivInt *p)
{
  bufAppend('(');
  bufAppend("DivInt");
  bufAppend(' ');
  p->expr_1->accept(this);
  bufAppend(' ');
  p->expr_2->accept(this);
  bufAppend(')');
}
void ShowAbsyn::visitMulReal(MulReal *p)
{
  bufAppend('(');
  bufAppend("MulReal");
  bufAppend(' ');
  p->expr_1->accept(this);
  bufAppend(' ');
  p->expr_2->accept(this);
  bufAppend(')');
}
void ShowAbsyn::visitDivReal(DivReal *p)
{
  bufAppend('(');
  bufAppend("DivReal");
  bufAppend(' ');
  p->expr_1->accept(this);
  bufAppend(' ');
  p->expr_2->accept(this);
  bufAppend(')');
}
void ShowAbsyn::visitEquInt(EquInt *p)
{
  bufAppend('(');
  bufAppend("EquInt");
  bufAppend(' ');
  p->expr_1->accept(this);
  bufAppend(' ');
  p->expr_2->accept(this);
  bufAppend(')');
}
void ShowAbsyn::visitLesInt(LesInt *p)
{
  bufAppend('(');
  bufAppend("LesInt");
  bufAppend(' ');
  p->expr_1->accept(this);
  bufAppend(' ');
  p->expr_2->accept(this);
  bufAppend(')');
}
void ShowAbsyn::visitEquReal(EquReal *p)
{
  bufAppend('(');
  bufAppend("EquReal");
  bufAppend(' ');
  p->expr_1->accept(this);
  bufAppend(' ');
  p->expr_2->accept(this);
  bufAppend(')');
}
void ShowAbsyn::visitLesReal(LesReal *p)
{
  bufAppend('(');
  bufAppend("LesReal");
  bufAppend(' ');
  p->expr_1->accept(this);
  bufAppend(' ');
  p->expr_2->accept(this);
  bufAppend(')');
}
void ShowAbsyn::visitListAbstractionField_(ListAbstractionField_ *listabstractionfield_)
{
  for (ListAbstractionField_::const_iterator i = listabstractionfield_->begin() ; i != listabstractionfield_->end() ; ++i)
  {
    (*i)->accept(this);
    if (i != listabstractionfield_->end() - 1) bufAppend(", ");
  }
}

void ShowAbsyn::visitAbstractionField_(AbstractionField_ *p) {} //abstract class

void ShowAbsyn::visitAbstractionField(AbstractionField *p)
{
  bufAppend('(');
  bufAppend("AbstractionField");
  bufAppend(' ');
  bufAppend('[');
  if (p->type_)  p->type_->accept(this);
  bufAppend(']');
  bufAppend(' ');
  visitIdent(p->ident_);
  bufAppend(')');
}
void ShowAbsyn::visitListWhereField_(ListWhereField_ *listwherefield_)
{
  for (ListWhereField_::const_iterator i = listwherefield_->begin() ; i != listwherefield_->end() ; ++i)
  {
    (*i)->accept(this);
    if (i != listwherefield_->end() - 1) bufAppend(", ");
  }
}

void ShowAbsyn::visitWhereField_(WhereField_ *p) {} //abstract class

void ShowAbsyn::visitWhereField(WhereField *p)
{
  bufAppend('(');
  bufAppend("WhereField");
  bufAppend(' ');
  visitIdent(p->ident_);
  bufAppend(' ');
  bufAppend('[');
  if (p->type_)  p->type_->accept(this);
  bufAppend(']');
  bufAppend(' ');
  bufAppend('[');
  if (p->expr_)  p->expr_->accept(this);
  bufAppend(']');
  bufAppend(')');
}
void ShowAbsyn::visitListRecordField_(ListRecordField_ *listrecordfield_)
{
  for (ListRecordField_::const_iterator i = listrecordfield_->begin() ; i != listrecordfield_->end() ; ++i)
  {
    (*i)->accept(this);
    if (i != listrecordfield_->end() - 1) bufAppend(", ");
  }
}

void ShowAbsyn::visitRecordField_(RecordField_ *p) {} //abstract class

void ShowAbsyn::visitRecordField(RecordField *p)
{
  bufAppend('(');
  bufAppend("RecordField");
  bufAppend(' ');
  visitIdent(p->ident_);
  bufAppend(' ');
  bufAppend('[');
  if (p->expr_)  p->expr_->accept(this);
  bufAppend(']');
  bufAppend(')');
}
void ShowAbsyn::visitListVariantField_(ListVariantField_ *listvariantfield_)
{
  for (ListVariantField_::const_iterator i = listvariantfield_->begin() ; i != listvariantfield_->end() ; ++i)
  {
    (*i)->accept(this);
    if (i != listvariantfield_->end() - 1) bufAppend(", ");
  }
}

void ShowAbsyn::visitVariantField_(VariantField_ *p) {} //abstract class

void ShowAbsyn::visitVariantField(VariantField *p)
{
  bufAppend('(');
  bufAppend("VariantField");
  bufAppend(' ');
  visitIdent(p->ident_1);
  bufAppend(' ');
  visitIdent(p->ident_2);
  bufAppend(' ');
  bufAppend('[');
  if (p->expr_)  p->expr_->accept(this);
  bufAppend(']');
  bufAppend(')');
}
void ShowAbsyn::visitStatement(Statement *p) {} //abstract class

void ShowAbsyn::visitImport(Import *p)
{
  bufAppend('(');
  bufAppend("Import");
  bufAppend(' ');
  visitIdent(p->ident_);
  bufAppend(' ');
  bufAppend(')');
}
void ShowAbsyn::visitDefinition(Definition *p)
{
  bufAppend('(');
  bufAppend("Definition");
  bufAppend(' ');
  bufAppend('[');
  if (p->type_)  p->type_->accept(this);
  bufAppend(']');
  bufAppend(' ');
  visitIdent(p->ident_);
  bufAppend(' ');
  bufAppend('[');
  if (p->expr_)  p->expr_->accept(this);
  bufAppend(']');
  bufAppend(')');
}
void ShowAbsyn::visitMoveAssignment(MoveAssignment *p)
{
  bufAppend('(');
  bufAppend("MoveAssignment");
  bufAppend(' ');
  p->expr_1->accept(this);
  bufAppend(' ');
  p->expr_2->accept(this);
  bufAppend(')');
}
void ShowAbsyn::visitCopyAssignment(CopyAssignment *p)
{
  bufAppend('(');
  bufAppend("CopyAssignment");
  bufAppend(' ');
  p->expr_1->accept(this);
  bufAppend(' ');
  p->expr_2->accept(this);
  bufAppend(')');
}
void ShowAbsyn::visitIfStatement(IfStatement *p)
{
  bufAppend('(');
  bufAppend("IfStatement");
  bufAppend(' ');
  bufAppend('[');
  if (p->expr_)  p->expr_->accept(this);
  bufAppend(']');
  bufAppend(' ');
  bufAppend('[');
  if (p->liststatement_)  p->liststatement_->accept(this);
  bufAppend(']');
  bufAppend(' ');
  bufAppend(')');
}
void ShowAbsyn::visitIfElseStatement(IfElseStatement *p)
{
  bufAppend('(');
  bufAppend("IfElseStatement");
  bufAppend(' ');
  bufAppend('[');
  if (p->expr_)  p->expr_->accept(this);
  bufAppend(']');
  bufAppend(' ');
  p->liststatement_1->accept(this);
  bufAppend(' ');
  p->liststatement_2->accept(this);
  bufAppend(' ');
  bufAppend(')');
}
void ShowAbsyn::visitLoop(Loop *p)
{
  bufAppend('(');
  bufAppend("Loop");
  bufAppend(' ');
  bufAppend('[');
  if (p->liststatement_)  p->liststatement_->accept(this);
  bufAppend(']');
  bufAppend(' ');
  bufAppend(')');
}
void ShowAbsyn::visitBreak(Break *p)
{
  bufAppend("Break");
}
void ShowAbsyn::visitContinue(Continue *p)
{
  bufAppend("Continue");
}
void ShowAbsyn::visitReturn(Return *p)
{
  bufAppend("Return");
}
void ShowAbsyn::visitEval(Eval *p)
{
  bufAppend('(');
  bufAppend("Eval");
  bufAppend(' ');
  bufAppend('[');
  if (p->expr_)  p->expr_->accept(this);
  bufAppend(']');
  bufAppend(')');
}
void ShowAbsyn::visitListStatement(ListStatement *liststatement)
{
  for (ListStatement::const_iterator i = liststatement->begin() ; i != liststatement->end() ; ++i)
  {
    (*i)->accept(this);
    if (i != liststatement->end() - 1) bufAppend(", ");
  }
}

void ShowAbsyn::visitListType(ListType *listtype)
{
  for (ListType::const_iterator i = listtype->begin() ; i != listtype->end() ; ++i)
  {
    (*i)->accept(this);
    if (i != listtype->end() - 1) bufAppend(", ");
  }
}

void ShowAbsyn::visitType(Type *p) {} //abstract class

void ShowAbsyn::visitAutoType(AutoType *p)
{
  bufAppend("AutoType");
}
void ShowAbsyn::visitBoolType(BoolType *p)
{
  bufAppend("BoolType");
}
void ShowAbsyn::visitNatType(NatType *p)
{
  bufAppend("NatType");
}
void ShowAbsyn::visitRefType(RefType *p)
{
  bufAppend('(');
  bufAppend("RefType");
  bufAppend(' ');
  bufAppend('[');
  if (p->type_)  p->type_->accept(this);
  bufAppend(']');
  bufAppend(')');
}
void ShowAbsyn::visitVarType(VarType *p)
{
  bufAppend('(');
  bufAppend("VarType");
  bufAppend(' ');
  visitIdent(p->ident_);
  bufAppend(')');
}
void ShowAbsyn::visitUniType(UniType *p)
{
  bufAppend('(');
  bufAppend("UniType");
  bufAppend(' ');
  visitIdent(p->ident_);
  bufAppend(' ');
  bufAppend('[');
  if (p->type_)  p->type_->accept(this);
  bufAppend(']');
  bufAppend(')');
}
void ShowAbsyn::visitFunType(FunType *p)
{
  bufAppend('(');
  bufAppend("FunType");
  bufAppend(' ');
  p->type_1->accept(this);
  bufAppend(' ');
  p->type_2->accept(this);
  bufAppend(')');
}
void ShowAbsyn::visitTupleType(TupleType *p)
{
  bufAppend('(');
  bufAppend("TupleType");
  bufAppend(' ');
  bufAppend('[');
  if (p->listtype_)  p->listtype_->accept(this);
  bufAppend(']');
  bufAppend(' ');
  bufAppend(')');
}
void ShowAbsyn::visitRecordType(RecordType *p)
{
  bufAppend('(');
  bufAppend("RecordType");
  bufAppend(' ');
  bufAppend('[');
  if (p->listrecordtypefield__)  p->listrecordtypefield__->accept(this);
  bufAppend(']');
  bufAppend(' ');
  bufAppend(')');
}
void ShowAbsyn::visitVariantType(VariantType *p)
{
  bufAppend('(');
  bufAppend("VariantType");
  bufAppend(' ');
  bufAppend('[');
  if (p->listvarianttypefield__)  p->listvarianttypefield__->accept(this);
  bufAppend(']');
  bufAppend(' ');
  bufAppend(')');
}
void ShowAbsyn::visitArrayType(ArrayType *p)
{
  bufAppend('(');
  bufAppend("ArrayType");
  bufAppend(' ');
  bufAppend('[');
  if (p->type_)  p->type_->accept(this);
  bufAppend(']');
  bufAppend(' ');
  bufAppend(')');
}
void ShowAbsyn::visitIntType(IntType *p)
{
  bufAppend("IntType");
}
void ShowAbsyn::visitRealType(RealType *p)
{
  bufAppend("RealType");
}
void ShowAbsyn::visitListRecordTypeField_(ListRecordTypeField_ *listrecordtypefield_)
{
  for (ListRecordTypeField_::const_iterator i = listrecordtypefield_->begin() ; i != listrecordtypefield_->end() ; ++i)
  {
    (*i)->accept(this);
    if (i != listrecordtypefield_->end() - 1) bufAppend(", ");
  }
}

void ShowAbsyn::visitRecordTypeField_(RecordTypeField_ *p) {} //abstract class

void ShowAbsyn::visitRecordTypeField(RecordTypeField *p)
{
  bufAppend('(');
  bufAppend("RecordTypeField");
  bufAppend(' ');
  visitIdent(p->ident_);
  bufAppend(' ');
  bufAppend('[');
  if (p->type_)  p->type_->accept(this);
  bufAppend(']');
  bufAppend(')');
}
void ShowAbsyn::visitListVariantTypeField_(ListVariantTypeField_ *listvarianttypefield_)
{
  for (ListVariantTypeField_::const_iterator i = listvarianttypefield_->begin() ; i != listvarianttypefield_->end() ; ++i)
  {
    (*i)->accept(this);
    if (i != listvarianttypefield_->end() - 1) bufAppend(", ");
  }
}

void ShowAbsyn::visitVariantTypeField_(VariantTypeField_ *p) {} //abstract class

void ShowAbsyn::visitVariantTypeField(VariantTypeField *p)
{
  bufAppend('(');
  bufAppend("VariantTypeField");
  bufAppend(' ');
  visitIdent(p->ident_);
  bufAppend(' ');
  bufAppend('[');
  if (p->type_)  p->type_->accept(this);
  bufAppend(']');
  bufAppend(')');
}
void ShowAbsyn::visitInteger(Integer i)
{
  char tmp[20];
  sprintf(tmp, "%d", i);
  bufAppend(tmp);
}
void ShowAbsyn::visitDouble(Double d)
{
  char tmp[24];
  sprintf(tmp, "%.15g", d);
  bufAppend(tmp);
}
void ShowAbsyn::visitChar(Char c)
{
  bufAppend('\'');
  bufAppend(c);
  bufAppend('\'');
}
void ShowAbsyn::visitString(String s)
{
  bufAppend('\"');
  bufAppend(s);
  bufAppend('\"');
}
void ShowAbsyn::visitIdent(String s)
{
  bufAppend('\"');
  bufAppend(s);
  bufAppend('\"');
}


