/* File generated by the BNF Converter (bnfc 2.9.4). */

/*** Visitor Design Pattern Skeleton. ***/
/* This implements the common visitor design pattern.
   Note that this method uses Visitor-traversal of lists, so
   List->accept() does NOT traverse the list. This allows different
   algorithms to use context information differently. */

#include "Skeleton.H"



void Skeleton::visitProgram(Program *t) {} //abstract class
void Skeleton::visitExpr(Expr *t) {} //abstract class
void Skeleton::visitAbstractionField_(AbstractionField_ *t) {} //abstract class
void Skeleton::visitWhereField_(WhereField_ *t) {} //abstract class
void Skeleton::visitRecordField_(RecordField_ *t) {} //abstract class
void Skeleton::visitVariantField_(VariantField_ *t) {} //abstract class
void Skeleton::visitStatement(Statement *t) {} //abstract class
void Skeleton::visitType(Type *t) {} //abstract class
void Skeleton::visitRecordTypeField_(RecordTypeField_ *t) {} //abstract class
void Skeleton::visitVariantTypeField_(VariantTypeField_ *t) {} //abstract class

void Skeleton::visitProgramRoot(ProgramRoot *program_root)
{
  /* Code For ProgramRoot Goes Here */

  if (program_root->liststatement_) program_root->liststatement_->accept(this);

}

void Skeleton::visitConstTrue(ConstTrue *const_true)
{
  /* Code For ConstTrue Goes Here */


}

void Skeleton::visitConstFalse(ConstFalse *const_false)
{
  /* Code For ConstFalse Goes Here */


}

void Skeleton::visitConstZero(ConstZero *const_zero)
{
  /* Code For ConstZero Goes Here */


}

void Skeleton::visitIf(If *if_)
{
  /* Code For If Goes Here */

  if (if_->expr_1) if_->expr_1->accept(this);
  if (if_->expr_2) if_->expr_2->accept(this);
  if (if_->expr_3) if_->expr_3->accept(this);

}

void Skeleton::visitSucc(Succ *succ)
{
  /* Code For Succ Goes Here */

  if (succ->expr_) succ->expr_->accept(this);

}

void Skeleton::visitPred(Pred *pred)
{
  /* Code For Pred Goes Here */

  if (pred->expr_) pred->expr_->accept(this);

}

void Skeleton::visitIsZero(IsZero *is_zero)
{
  /* Code For IsZero Goes Here */

  if (is_zero->expr_) is_zero->expr_->accept(this);

}

void Skeleton::visitVar(Var *var)
{
  /* Code For Var Goes Here */

  visitIdent(var->ident_);

}

void Skeleton::visitAbstraction(Abstraction *abstraction)
{
  /* Code For Abstraction Goes Here */

  if (abstraction->type_) abstraction->type_->accept(this);
  visitIdent(abstraction->ident_);
  if (abstraction->liststatement_) abstraction->liststatement_->accept(this);
  if (abstraction->expr_) abstraction->expr_->accept(this);

}

void Skeleton::visitMultiAbstraction(MultiAbstraction *multi_abstraction)
{
  /* Code For MultiAbstraction Goes Here */

  if (multi_abstraction->listabstractionfield__) multi_abstraction->listabstractionfield__->accept(this);
  if (multi_abstraction->liststatement_) multi_abstraction->liststatement_->accept(this);
  if (multi_abstraction->expr_) multi_abstraction->expr_->accept(this);

}

void Skeleton::visitApplication(Application *application)
{
  /* Code For Application Goes Here */

  if (application->expr_1) application->expr_1->accept(this);
  if (application->expr_2) application->expr_2->accept(this);

}

void Skeleton::visitTypeAbstraction(TypeAbstraction *type_abstraction)
{
  /* Code For TypeAbstraction Goes Here */

  visitIdent(type_abstraction->ident_);
  if (type_abstraction->expr_) type_abstraction->expr_->accept(this);

}

void Skeleton::visitTypeApplication(TypeApplication *type_application)
{
  /* Code For TypeApplication Goes Here */

  if (type_application->expr_) type_application->expr_->accept(this);
  if (type_application->type_) type_application->type_->accept(this);

}

void Skeleton::visitFix(Fix *fix)
{
  /* Code For Fix Goes Here */

  if (fix->expr_) fix->expr_->accept(this);

}

void Skeleton::visitWhere(Where *where)
{
  /* Code For Where Goes Here */

  if (where->expr_1) where->expr_1->accept(this);
  if (where->type_) where->type_->accept(this);
  visitIdent(where->ident_);
  if (where->expr_2) where->expr_2->accept(this);

}

void Skeleton::visitMultiWhere(MultiWhere *multi_where)
{
  /* Code For MultiWhere Goes Here */

  if (multi_where->expr_) multi_where->expr_->accept(this);
  if (multi_where->listwherefield__) multi_where->listwherefield__->accept(this);

}

void Skeleton::visitReference(Reference *reference)
{
  /* Code For Reference Goes Here */

  if (reference->expr_) reference->expr_->accept(this);

}

void Skeleton::visitDereference(Dereference *dereference)
{
  /* Code For Dereference Goes Here */

  if (dereference->expr_) dereference->expr_->accept(this);

}

void Skeleton::visitTuple(Tuple *tuple)
{
  /* Code For Tuple Goes Here */

  if (tuple->listexpr_) tuple->listexpr_->accept(this);

}

void Skeleton::visitTupleGet(TupleGet *tuple_get)
{
  /* Code For TupleGet Goes Here */

  if (tuple_get->expr_) tuple_get->expr_->accept(this);
  visitInteger(tuple_get->integer_);

}

void Skeleton::visitRecord(Record *record)
{
  /* Code For Record Goes Here */

  if (record->listrecordfield__) record->listrecordfield__->accept(this);

}

void Skeleton::visitRecordGet(RecordGet *record_get)
{
  /* Code For RecordGet Goes Here */

  if (record_get->expr_) record_get->expr_->accept(this);
  visitIdent(record_get->ident_);

}

void Skeleton::visitVariant(Variant *variant)
{
  /* Code For Variant Goes Here */

  visitIdent(variant->ident_);
  if (variant->expr_) variant->expr_->accept(this);
  if (variant->type_) variant->type_->accept(this);

}

void Skeleton::visitVariantCase(VariantCase *variant_case)
{
  /* Code For VariantCase Goes Here */

  if (variant_case->expr_) variant_case->expr_->accept(this);
  if (variant_case->listvariantfield__) variant_case->listvariantfield__->accept(this);

}

void Skeleton::visitArray(Array *array)
{
  /* Code For Array Goes Here */

  if (array->listexpr_) array->listexpr_->accept(this);

}

void Skeleton::visitArrayGet(ArrayGet *array_get)
{
  /* Code For ArrayGet Goes Here */

  if (array_get->expr_1) array_get->expr_1->accept(this);
  if (array_get->expr_2) array_get->expr_2->accept(this);

}

void Skeleton::visitArrayPush(ArrayPush *array_push)
{
  /* Code For ArrayPush Goes Here */

  if (array_push->expr_1) array_push->expr_1->accept(this);
  if (array_push->expr_2) array_push->expr_2->accept(this);

}

void Skeleton::visitArrayPop(ArrayPop *array_pop)
{
  /* Code For ArrayPop Goes Here */

  if (array_pop->expr_) array_pop->expr_->accept(this);

}

void Skeleton::visitArrayLen(ArrayLen *array_len)
{
  /* Code For ArrayLen Goes Here */

  if (array_len->expr_) array_len->expr_->accept(this);

}

void Skeleton::visitConstInt(ConstInt *const_int)
{
  /* Code For ConstInt Goes Here */

  visitInteger(const_int->integer_);

}

void Skeleton::visitToInt(ToInt *to_int)
{
  /* Code For ToInt Goes Here */

  if (to_int->expr_) to_int->expr_->accept(this);

}

void Skeleton::visitAddInt(AddInt *add_int)
{
  /* Code For AddInt Goes Here */

  if (add_int->expr_1) add_int->expr_1->accept(this);
  if (add_int->expr_2) add_int->expr_2->accept(this);

}

void Skeleton::visitSubInt(SubInt *sub_int)
{
  /* Code For SubInt Goes Here */

  if (sub_int->expr_1) sub_int->expr_1->accept(this);
  if (sub_int->expr_2) sub_int->expr_2->accept(this);

}

void Skeleton::visitMulInt(MulInt *mul_int)
{
  /* Code For MulInt Goes Here */

  if (mul_int->expr_1) mul_int->expr_1->accept(this);
  if (mul_int->expr_2) mul_int->expr_2->accept(this);

}

void Skeleton::visitDivInt(DivInt *div_int)
{
  /* Code For DivInt Goes Here */

  if (div_int->expr_1) div_int->expr_1->accept(this);
  if (div_int->expr_2) div_int->expr_2->accept(this);

}

void Skeleton::visitEquInt(EquInt *equ_int)
{
  /* Code For EquInt Goes Here */

  if (equ_int->expr_1) equ_int->expr_1->accept(this);
  if (equ_int->expr_2) equ_int->expr_2->accept(this);

}

void Skeleton::visitLesInt(LesInt *les_int)
{
  /* Code For LesInt Goes Here */

  if (les_int->expr_1) les_int->expr_1->accept(this);
  if (les_int->expr_2) les_int->expr_2->accept(this);

}

void Skeleton::visitConstReal(ConstReal *const_real)
{
  /* Code For ConstReal Goes Here */

  visitDouble(const_real->double_);

}

void Skeleton::visitToReal(ToReal *to_real)
{
  /* Code For ToReal Goes Here */

  if (to_real->expr_) to_real->expr_->accept(this);

}

void Skeleton::visitAddReal(AddReal *add_real)
{
  /* Code For AddReal Goes Here */

  if (add_real->expr_1) add_real->expr_1->accept(this);
  if (add_real->expr_2) add_real->expr_2->accept(this);

}

void Skeleton::visitSubReal(SubReal *sub_real)
{
  /* Code For SubReal Goes Here */

  if (sub_real->expr_1) sub_real->expr_1->accept(this);
  if (sub_real->expr_2) sub_real->expr_2->accept(this);

}

void Skeleton::visitMulReal(MulReal *mul_real)
{
  /* Code For MulReal Goes Here */

  if (mul_real->expr_1) mul_real->expr_1->accept(this);
  if (mul_real->expr_2) mul_real->expr_2->accept(this);

}

void Skeleton::visitDivReal(DivReal *div_real)
{
  /* Code For DivReal Goes Here */

  if (div_real->expr_1) div_real->expr_1->accept(this);
  if (div_real->expr_2) div_real->expr_2->accept(this);

}

void Skeleton::visitEquReal(EquReal *equ_real)
{
  /* Code For EquReal Goes Here */

  if (equ_real->expr_1) equ_real->expr_1->accept(this);
  if (equ_real->expr_2) equ_real->expr_2->accept(this);

}

void Skeleton::visitLesReal(LesReal *les_real)
{
  /* Code For LesReal Goes Here */

  if (les_real->expr_1) les_real->expr_1->accept(this);
  if (les_real->expr_2) les_real->expr_2->accept(this);

}

void Skeleton::visitReadInt(ReadInt *read_int)
{
  /* Code For ReadInt Goes Here */


}

void Skeleton::visitReadReal(ReadReal *read_real)
{
  /* Code For ReadReal Goes Here */


}

void Skeleton::visitWriteInt(WriteInt *write_int)
{
  /* Code For WriteInt Goes Here */

  if (write_int->expr_) write_int->expr_->accept(this);

}

void Skeleton::visitWriteReal(WriteReal *write_real)
{
  /* Code For WriteReal Goes Here */

  if (write_real->expr_) write_real->expr_->accept(this);

}

void Skeleton::visitAbstractionField(AbstractionField *abstraction_field)
{
  /* Code For AbstractionField Goes Here */

  if (abstraction_field->type_) abstraction_field->type_->accept(this);
  visitIdent(abstraction_field->ident_);

}

void Skeleton::visitWhereField(WhereField *where_field)
{
  /* Code For WhereField Goes Here */

  if (where_field->type_) where_field->type_->accept(this);
  visitIdent(where_field->ident_);
  if (where_field->expr_) where_field->expr_->accept(this);

}

void Skeleton::visitRecordField(RecordField *record_field)
{
  /* Code For RecordField Goes Here */

  visitIdent(record_field->ident_);
  if (record_field->expr_) record_field->expr_->accept(this);

}

void Skeleton::visitVariantField(VariantField *variant_field)
{
  /* Code For VariantField Goes Here */

  visitIdent(variant_field->ident_1);
  visitIdent(variant_field->ident_2);
  if (variant_field->expr_) variant_field->expr_->accept(this);

}

void Skeleton::visitImport(Import *import)
{
  /* Code For Import Goes Here */

  visitString(import->string_);

}

void Skeleton::visitDefinition(Definition *definition)
{
  /* Code For Definition Goes Here */

  if (definition->type_) definition->type_->accept(this);
  visitIdent(definition->ident_);
  if (definition->expr_) definition->expr_->accept(this);

}

void Skeleton::visitTypeDefinition(TypeDefinition *type_definition)
{
  /* Code For TypeDefinition Goes Here */

  visitIdent(type_definition->ident_);
  if (type_definition->type_) type_definition->type_->accept(this);

}

void Skeleton::visitAssignment(Assignment *assignment)
{
  /* Code For Assignment Goes Here */

  if (assignment->expr_1) assignment->expr_1->accept(this);
  if (assignment->expr_2) assignment->expr_2->accept(this);

}

void Skeleton::visitIfStatement(IfStatement *if_statement)
{
  /* Code For IfStatement Goes Here */

  if (if_statement->expr_) if_statement->expr_->accept(this);
  if (if_statement->liststatement_) if_statement->liststatement_->accept(this);

}

void Skeleton::visitIfElseStatement(IfElseStatement *if_else_statement)
{
  /* Code For IfElseStatement Goes Here */

  if (if_else_statement->expr_) if_else_statement->expr_->accept(this);
  if (if_else_statement->liststatement_1) if_else_statement->liststatement_1->accept(this);
  if (if_else_statement->liststatement_2) if_else_statement->liststatement_2->accept(this);

}

void Skeleton::visitLoop(Loop *loop)
{
  /* Code For Loop Goes Here */

  if (loop->liststatement_) loop->liststatement_->accept(this);

}

void Skeleton::visitBreak(Break *break_)
{
  /* Code For Break Goes Here */


}

void Skeleton::visitContinue(Continue *continue_)
{
  /* Code For Continue Goes Here */


}

void Skeleton::visitReturn(Return *return_)
{
  /* Code For Return Goes Here */


}

void Skeleton::visitEval(Eval *eval)
{
  /* Code For Eval Goes Here */

  if (eval->expr_) eval->expr_->accept(this);

}

void Skeleton::visitAutoType(AutoType *auto_type)
{
  /* Code For AutoType Goes Here */


}

void Skeleton::visitBoolType(BoolType *bool_type)
{
  /* Code For BoolType Goes Here */


}

void Skeleton::visitNatType(NatType *nat_type)
{
  /* Code For NatType Goes Here */


}

void Skeleton::visitRefType(RefType *ref_type)
{
  /* Code For RefType Goes Here */

  if (ref_type->type_) ref_type->type_->accept(this);

}

void Skeleton::visitVarType(VarType *var_type)
{
  /* Code For VarType Goes Here */

  visitIdent(var_type->ident_);

}

void Skeleton::visitUniType(UniType *uni_type)
{
  /* Code For UniType Goes Here */

  visitIdent(uni_type->ident_);
  if (uni_type->type_) uni_type->type_->accept(this);

}

void Skeleton::visitFunType(FunType *fun_type)
{
  /* Code For FunType Goes Here */

  if (fun_type->type_1) fun_type->type_1->accept(this);
  if (fun_type->type_2) fun_type->type_2->accept(this);

}

void Skeleton::visitTupleType(TupleType *tuple_type)
{
  /* Code For TupleType Goes Here */

  if (tuple_type->listtype_) tuple_type->listtype_->accept(this);

}

void Skeleton::visitRecordType(RecordType *record_type)
{
  /* Code For RecordType Goes Here */

  if (record_type->listrecordtypefield__) record_type->listrecordtypefield__->accept(this);

}

void Skeleton::visitVariantType(VariantType *variant_type)
{
  /* Code For VariantType Goes Here */

  if (variant_type->listvarianttypefield__) variant_type->listvarianttypefield__->accept(this);

}

void Skeleton::visitArrayType(ArrayType *array_type)
{
  /* Code For ArrayType Goes Here */

  if (array_type->type_) array_type->type_->accept(this);

}

void Skeleton::visitIntType(IntType *int_type)
{
  /* Code For IntType Goes Here */


}

void Skeleton::visitRealType(RealType *real_type)
{
  /* Code For RealType Goes Here */


}

void Skeleton::visitRecordTypeField(RecordTypeField *record_type_field)
{
  /* Code For RecordTypeField Goes Here */

  visitIdent(record_type_field->ident_);
  if (record_type_field->type_) record_type_field->type_->accept(this);

}

void Skeleton::visitVariantTypeField(VariantTypeField *variant_type_field)
{
  /* Code For VariantTypeField Goes Here */

  visitIdent(variant_type_field->ident_);
  if (variant_type_field->type_) variant_type_field->type_->accept(this);

}


void Skeleton::visitListExpr(ListExpr *list_expr)
{
  for (ListExpr::iterator i = list_expr->begin() ; i != list_expr->end() ; ++i)
  {
    (*i)->accept(this);
  }
}

void Skeleton::visitListAbstractionField_(ListAbstractionField_ *list_abstraction_field)
{
  for (ListAbstractionField_::iterator i = list_abstraction_field->begin() ; i != list_abstraction_field->end() ; ++i)
  {
    (*i)->accept(this);
  }
}

void Skeleton::visitListWhereField_(ListWhereField_ *list_where_field)
{
  for (ListWhereField_::iterator i = list_where_field->begin() ; i != list_where_field->end() ; ++i)
  {
    (*i)->accept(this);
  }
}

void Skeleton::visitListRecordField_(ListRecordField_ *list_record_field)
{
  for (ListRecordField_::iterator i = list_record_field->begin() ; i != list_record_field->end() ; ++i)
  {
    (*i)->accept(this);
  }
}

void Skeleton::visitListVariantField_(ListVariantField_ *list_variant_field)
{
  for (ListVariantField_::iterator i = list_variant_field->begin() ; i != list_variant_field->end() ; ++i)
  {
    (*i)->accept(this);
  }
}

void Skeleton::visitListStatement(ListStatement *list_statement)
{
  for (ListStatement::iterator i = list_statement->begin() ; i != list_statement->end() ; ++i)
  {
    (*i)->accept(this);
  }
}

void Skeleton::visitListType(ListType *list_type)
{
  for (ListType::iterator i = list_type->begin() ; i != list_type->end() ; ++i)
  {
    (*i)->accept(this);
  }
}

void Skeleton::visitListRecordTypeField_(ListRecordTypeField_ *list_record_type_field)
{
  for (ListRecordTypeField_::iterator i = list_record_type_field->begin() ; i != list_record_type_field->end() ; ++i)
  {
    (*i)->accept(this);
  }
}

void Skeleton::visitListVariantTypeField_(ListVariantTypeField_ *list_variant_type_field)
{
  for (ListVariantTypeField_::iterator i = list_variant_type_field->begin() ; i != list_variant_type_field->end() ; ++i)
  {
    (*i)->accept(this);
  }
}


void Skeleton::visitInteger(Integer x)
{
  /* Code for Integer Goes Here */
}

void Skeleton::visitChar(Char x)
{
  /* Code for Char Goes Here */
}

void Skeleton::visitDouble(Double x)
{
  /* Code for Double Goes Here */
}

void Skeleton::visitString(String x)
{
  /* Code for String Goes Here */
}

void Skeleton::visitIdent(Ident x)
{
  /* Code for Ident Goes Here */
}



